/* Optional timing helpers: boundaries, validation and out-of-order evaluation. */
const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const context = vm.createContext({ window: {} });
for (const file of ['lib/motion.js', 'lib/timing.js']) vm.runInContext(fs.readFileSync(file, 'utf8'), context);
const { keyframes, beatClock, boil, shots } = context.window.PV;
const near = (a, b) => assert(Math.abs(a - b) < 1e-10, `${a} != ${b}`);
const curve = keyframes([[1, [0, 10]], [3, [20, 30]], [4, [10, 20]]]);
assert.equal(JSON.stringify(curve(2)), '[10,20]');
assert.equal(JSON.stringify(curve(-1)), '[0,10]');
assert.equal(JSON.stringify(curve(9)), '[10,20]');
const value = curve(1); value[0] = 99;
assert.equal(curve(1)[0], 0);
near(keyframes([[0, 0], [2, 8]], x => x*x)(1), 2);
for (const keys of [[], [[0, 1], [0, 2]], [[1, 1], [0, 2]], [[0, [1]], [1, [2, 3]]], [[0, NaN]]]) assert.throws(() => keyframes(keys));
const clock = beatClock(120, 0.25);
near(clock.time(3), 1.75); near(clock.position(1.75), 3);
near(clock.pulse(0.25), 1); near(clock.pulse(0.5, 2), 1);
assert(clock.pulse(0.4) < 1); assert.equal(clock.pulse(0.1), 0);
assert.throws(() => beatClock(0)); assert.throws(() => clock.pulse(1, 0));
const jitter = boil(0.1, 'edge', 12, 7);
assert.equal(jitter, boil(0.15, 'edge', 12, 7));
assert.notEqual(jitter, boil(0.2, 'edge', 12, 7));
assert.notEqual(jitter, boil(0.1, 'other', 12, 7));
assert(jitter >= -1 && jitter <= 1); assert.throws(() => boil(0, 'edge', 0));
const track = shots([[1, 'a'], [3, 'b']], 5);
assert.equal(track(0), null); assert.equal(track(5), null);
assert.equal(track(3).value, 'b'); near(track(3).local, 0); near(track(3).duration, 2);
assert.equal(track(2).value, 'a'); near(track(2).duration, 2);
assert.throws(() => shots([[1, 'a']], 1));
const times = [4, 1, 2.5, 0, 3, 2.5];
const baseline = new Map(times.map(t => [t, JSON.stringify(curve(t))]));
for (const t of times.slice().reverse()) assert.equal(JSON.stringify(curve(t)), baseline.get(t));
const source = [[0, [1, 2]], [1, [3, 4]]];
const snapshot = keyframes(source); source[0][1][0] = 500; source[1][0] = 90;
assert.equal(JSON.stringify(snapshot(0.5)), '[2,3]');
for (const helper of [curve, track, clock.position]) assert.throws(() => helper(NaN));
assert.throws(() => shots([[1, 'a'], [1, 'b']], 5));
assert.equal(boil(-0.1, 'edge'), boil(-0.1, 'edge'));
console.log('PASS timing: interpolation, ownership, invalid input, beat boundaries, boil and shot cuts');
